# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#
#    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

a = 1
b = 2
maxval = 4000000
total = 2

print a
print b

new = a + b
while (1):
    if new < maxval:
        new = a + b
        a = b
        b = new
        print new
        if new % 2 is 0:
            total = total + new
    else:
        break

print "Sum total for even fibonnacci less than 4 million = %d" % (total)
